repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.6.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-merge-conflict
      - id: check-executables-have-shebangs
      - id: check-toml
      - id: check-yaml
      # - id: no-commit-to-branch
      #   args: ["--branch", "main"]
  - repo: https://github.com/astral-sh/ruff-pre-commit
    # Ruff version.
    rev: v0.6.4
    hooks:
      # Run the linter.
      - id: ruff
        args: [--fix, --exit-non-zero-on-fix]
      # Run the formatter.
      - id: ruff-format
  - repo: local
    hooks:
      - id: pyright
        name: pyright
        description: "Run pyright on python files"
        entry: bash ci/lint-pyright.sh
        language: system
        types_or: [python, pyi]
        exclude: "^third_party/"
